Components
TemesgenA/calculator-app pull request #2
Opened 2022-10-27 15:00 UTC by TemesgenA

## Features implemented
- Create a class-based component

2022-10-27 18:06 UTC, OLIPLICHE requested changes
Hi @TemesgenA, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used (Pull Request is made from the feature branch into the dev branch) 👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 18:06 UTC, OLIPLICHE commented on src/App.js
>      <div className="App">
- Please The App.js component should be class-based.
- After making the change, make sure that the calculator should render without problems

2022-10-28 20:49 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @TemesgenA,

Good job so far on making the changes asked by the previous reviewer!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly 👍 
✅ Linter checks 👍 

## Required Changes ♻️
_Check the comments under the review._
There are a few changes you should work on that the previous reviewer did not mention which is a great requirement. Please consider the following below:

- [ ] It would be nice if you could follow the calculator app design given as much as you can. I noticed from your design, the order of the numbers is not aligned as in the original design and as well as the color. It's required that your design match the given design.

**The Original Design**
![image](https://user-images.githubusercontent.com/50941074/198729340-1269fa7b-5e9d-4479-b176-79320ee772b8.png)

**Your design**
![image](https://user-images.githubusercontent.com/50941074/198729514-30b6bdf8-6261-4408-8bbb-d3de2af58444.png)

- [ ] You are almost there. Kindly switch the order of the numbering and work on the color of the app and your app will be on its way to approval. Please 👍  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-28 20:59 UTC, TemesgenA commented
Hey there,
Thanks for the review.
I'll Fix the order of the numbers. But concerning the color of the buttons, Is that required?

2022-10-28 21:22 UTC, AmaduKamara commented
Basically, the requirement said, your design must match the one given and I'm sure that too should be considered brother. Maybe in the final complete site, you can change things up and have colors of your choice. 👍

2022-10-28 22:39 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @TemesgenA,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-28 22:43 UTC, merged